// Copyright (c) 2025 g41797
// SPDX-License-Identifier: MIT

//
// Initial implementation was generated by Grok
//
pub fn copyFields(comptime T1: type, comptime T2: type, src: anytype, dest: anytype) usize {
    const fields1 = comptime @typeInfo(T1).@"struct".fields;

    var count: usize = 0;

    inline for (fields1) |field1| {
        if (@hasField(T2, field1.name)) {
            @field(dest, field1.name) = @field(src, field1.name);
            count += 1;
        }
    }

    return count;
}

const std = @import("std");
const string = []const u8;

