name: Windows

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows]

    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: mlugg/setup-zig@v1
        with:
          version:   0.14.0
          use-cache: false
      
      - run: ./bin/windows/nats-server.exe  -js -m 8222 &

      - name: Sleep for 2 seconds
        run: Start-Sleep -s 2
        shell: powershell
       
#      - run: zig build test -freference-trace --summary all

